config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :user_sessions

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :contracts

  resources :note_styles

  resources :notes

  resources :dep_people

  resources :people

  resources :additional_day_infos

  resources :departments

  resources :years

  resources :users

  root 'departments#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :dep_person
  has_and_belongs_to_many :note_styles

  validates :start, presence: true
  validates :finish, presence: true  
  validates :dep_person_id, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:start, :finish, :dep_person_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br>
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :finish %><br>
    <%= f.date_select :finish %>
  </div>
  <div class="field">
    <%= f.label :dep_person_id %><br>
    <%= f.text_field :dep_person_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Редактирование заметки</h1>

<%= render 'form' %>

<%= link_to 'Показать', @note %> |
<%= link_to 'Назад', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список заметок</h1>

<table>
  <thead>
    <tr>
      <th>С</th>
      <th>По</th>
      <th>Dep person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.start %></td>
        <td><%= note.finish %></td>
        <td><%= note.dep_person %></td>
        <td><%= link_to 'Показать', note %></td>
        <td><%= link_to 'Редактировать', edit_note_path(note) %></td>
        <td><%= link_to 'Удалить', note, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новая заметка', new_note_path %>

app/views/notes/new.html.erb
<h1>Новая заметка</h1>

<%= render 'form' %>

<%= link_to 'Назад', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>С:</strong>
  <%= @note.start %>
</p>

<p>
  <strong>По:</strong>
  <%= @note.finish %>
</p>

<p>
  <strong>Dep person:</strong>
  <%= @note.dep_person %>
</p>

<%= link_to 'Редактировать', edit_note_path(@note) %> |
<%= link_to 'Назад', notes_path %>