config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :user_sessions

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :contracts

  resources :note_styles

  resources :notes

  resources :dep_people

  resources :people

  resources :additional_day_infos

  resources :departments

  resources :years

  resources :users

  root 'departments#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :dep_people, dependent: :destroy

  validates :first_name, presence: true
  validates :second_name, presence: true
  validates :last_name, presence: true
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :second_name, :last_name, :external_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :second_name %><br>
    <%= f.text_field :second_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :external_id %><br>
    <%= f.number_field :external_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Редактировать человека</h1>

<%= render 'form' %>

<%= link_to 'Показать', @person %> |
<%= link_to 'Назад', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список людей</h1>

<table>
  <thead>
    <tr>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Отчество</th>
      <th>External</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.second_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.external_id %></td>
        <td><%= link_to 'Показать', person %></td>
        <td><%= link_to 'Редактировать', edit_person_path(person) %></td>
        <td><%= link_to 'Удалить', person, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить человека', new_person_path %>

app/views/people/new.html.erb
<h1>Новый человек</h1>

<%= render 'form' %>

<%= link_to 'Назад', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Имя:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Фамилия:</strong>
  <%= @person.second_name %>
</p>

<p>
  <strong>Отчество:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>External:</strong>
  <%= @person.external_id %>
</p>

<%= link_to 'Редактировать', edit_person_path(@person) %> |
<%= link_to 'Назад', people_path %>