config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :user_sessions

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :contracts

  resources :note_styles

  resources :notes

  resources :dep_people

  resources :people

  resources :additional_day_infos

  resources :departments

  resources :years

  resources :users

  root 'departments#index'

end

app/models/note_style.rb
class NoteStyle < ActiveRecord::Base
  has_and_belongs_to_many :notes
  
  validates :name, presence: true
  validates :code, presence: true
  validates :style, :inclusion => {:in => [true, false]}
  validate :check_name_code

  def check_name_code
    if name="Я" && code!="01"
      errors.add(:code,:invalid)
    end 
  end
end

app/controllers/note_styles_controller.rb
class NoteStylesController < ApplicationController
  before_action :set_note_style, only: [:show, :edit, :update, :destroy]

  # GET /note_styles
  # GET /note_styles.json
  def index
    @note_styles = NoteStyle.all
  end

  # GET /note_styles/1
  # GET /note_styles/1.json
  def show
  end

  # GET /note_styles/new
  def new
    @note_style = NoteStyle.new
  end

  # GET /note_styles/1/edit
  def edit
  end

  # POST /note_styles
  # POST /note_styles.json
  def create
    @note_style = NoteStyle.new(note_style_params)

    respond_to do |format|
      if @note_style.save
        format.html { redirect_to @note_style, notice: 'Note style was successfully created.' }
        format.json { render :show, status: :created, location: @note_style }
      else
        format.html { render :new }
        format.json { render json: @note_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /note_styles/1
  # PATCH/PUT /note_styles/1.json
  def update
    respond_to do |format|
      if @note_style.update(note_style_params)
        format.html { redirect_to @note_style, notice: 'Note style was successfully updated.' }
        format.json { render :show, status: :ok, location: @note_style }
      else
        format.html { render :edit }
        format.json { render json: @note_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /note_styles/1
  # DELETE /note_styles/1.json
  def destroy
    @note_style.destroy
    respond_to do |format|
      format.html { redirect_to note_styles_url, notice: 'Note style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note_style
      @note_style = NoteStyle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_style_params
      params.require(:note_style).permit(:name, :code, :style)
    end
end

app/helpers/note_styles_helper.rb
module NoteStylesHelper
end

app/views/note_styles/_form.html.erb
<%= form_for(@note_style) do |f| %>
  <% if @note_style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note_style.errors.count, "error") %> prohibited this note_style from being saved:</h2>

      <ul>
      <% @note_style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :style %><br>
    <%= f.check_box :style %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/note_styles/edit.html.erb
<h1>Редактировать тип заметки</h1>

<%= render 'form' %>

<%= link_to 'Показать', @note_style %> |
<%= link_to 'Назад', note_styles_path %>

app/views/note_styles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список типов заметок</h1>

<table>
  <thead>
    <tr>
      <th>Буквенный код</th>
      <th>Цифровой код</th>
      <th>Считывать?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @note_styles.each do |note_style| %>
      <tr>
        <td><%= note_style.name %></td>
        <td><%= note_style.code %></td>
        <td><%= note_style.style %></td>
        <td><%= link_to 'Показать', note_style %></td>
        <td><%= link_to 'Редактировать', edit_note_style_path(note_style) %></td>
        <td><%= link_to 'Удалить', note_style, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Создать тип заметки', new_note_style_path %>

app/views/note_styles/new.html.erb
<h1>Создание типа заметки</h1>

<%= render 'form' %>

<%= link_to 'Назад', note_styles_path %>

app/views/note_styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Буквенный код:</strong>
  <%= @note_style.name %>
</p>

<p>
  <strong>Цифровой код:</strong>
  <%= @note_style.code %>
</p>

<p>
  <strong>Считывать?:</strong>
  <%= @note_style.style %>
</p>

<%= link_to 'Редактировать', edit_note_style_path(@note_style) %> |
<%= link_to 'Назад', note_styles_path %>