config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :user_sessions

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :contracts

  resources :note_styles

  resources :notes

  resources :dep_people

  resources :people

  resources :additional_day_infos

  resources :departments

  resources :years

  resources :users

  root 'departments#index'

end

app/models/additional_day_info.rb
class AdditionalDayInfo < ActiveRecord::Base
  belongs_to :year

  validates :year_id, presence: true
  validates :day, presence: true
  validates :style, presence: true
  
  DAYSTYLE=["Рабочий день для всех", "Рабочий день для работников с 6-дневной рабочей неделей", "Выходной (праздник)", "Выходной для работников с 5-дневной рабочей неделей", "Короткий день"]
  
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  has_many :dep_people, dependent: :destroy

  validates :post, presence: true
  validates :rate, presence: true
  validates :budget, presence: true
  validates :style, presence: true
  validates :start, presence: true 
  validates :finish, presence: true
  
  RATE=["1", "0.75", "0.5", "0.25"]
  BUDGET=["Бюджет","Внебюджет"]
  STYLE=["Совместительтво","Штат","Контракт","Почасовик"]
end

app/models/dep_person.rb
class DepPerson < ActiveRecord::Base
  belongs_to :department
  belongs_to :contract
  belongs_to :person

  validates :department_id, presence: true
  validates :contract_id, presence: true
  validates :person_id, presence: true
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :year
  has_many :dep_people, dependent: :destroy
  has_and_belongs_to_many :users
  
  validates :style, presence: true
  validates :name, presence: true
  validates :director, presence: true
  validates :responsible, presence: true
  validates :year_id, presence: true
  
  DEPSTYLE=["ППС","УВП","ППС/УВП"]
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :dep_person
  has_and_belongs_to_many :note_styles

  validates :start, presence: true
  validates :finish, presence: true  
  validates :dep_person_id, presence: true
end

app/models/note_style.rb
class NoteStyle < ActiveRecord::Base
  has_and_belongs_to_many :notes
  
  validates :name, presence: true
  validates :code, presence: true
  validates :style, :inclusion => {:in => [true, false]}
  validate :check_name_code

  def check_name_code
    if name="Я" && code!="01"
      errors.add(:code,:invalid)
    end 
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :dep_people, dependent: :destroy

  validates :first_name, presence: true
  validates :second_name, presence: true
  validates :last_name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_and_belongs_to_many :departments

  validates :username, presence: true, uniqueness: true
  validates_presence_of :password, if: :password_required?
  validates_confirmation_of :password, if: :password_required?
  validates_length_of :password, within: 5..255, allow_blank: true
 
  validates :first_name, presence: true
  validates :second_name, presence: true
  validates :last_name, presence: true

  validates :is_operator, :inclusion => {:in => [true, false]}
  validates :is_admin, :inclusion => {:in => [true, false]}

  def admin?
    self.is_admin == true
  end
  def operator?
    self.is_operator == true
  end
  private
  def default_values
    self.is_operator ||= false
    self.is_admin ||= false
  end
  def password_required?
    password.present? || password_confirmation.present?
  end
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :departments, dependent: :destroy
  has_many :additional_day_infos, dependent: :destroy

  validates :name, presence: true
  validates :is_current, :inclusion => {:in => [true, false]}
  validates :month, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:start, :finish, :dep_person_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Пользователь успешно создан.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Пользователь успешно изменен.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Пользователь успешно удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :second_name, :last_name, :username, :password, :is_operator, :is_admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def selectify(arr)
    res=[]
    for i in 0...arr.size
      res << [arr[i],i]
    end
    res
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/dep_people_helper.rb
module DepPeopleHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/note_styles_helper.rb
module NoteStylesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/layouts/_user_admin.html.erb
<% loginText  = current_user.try(:second_name) + ' ' + current_user.try(:first_name) + ' ' + current_user.try(:last_name) %>
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_url %>">
        <img height="13px" src="/assets/logo.png"/>
      </a>
      <button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Отделы", departments_path %>
        </li>
        <li>
          <%= link_to "Пользователи", users_path %>
        </li>
        <li>
          <%= link_to  loginText +" (Выход)", logout_path %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_user_admin.html.haml
- currentYear = StudyYear.current.first
- loginText  = current_user.try(:second_name) + ' ' + current_user.try(:first_name) + ' ' + current_user.try(:last_name)
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %a.navbar-brand{:href => root_url}
        %img{:src => "/assets/logo.png", :height => "13px"}
        - unless currentYear.nil?
          = currentYear.name
      %button.navbar-toggle{"data-target" => "#navbar-main", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbar-main.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          =link_to "Кафедры", departments_path
        %li
          =link_to "Список пользователей", users_path
        %li
          =link_to "Года", years_path
        %li
          =link_to  loginText +" (Выход)", logout_path

app/views/layouts/_user_not_logged.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_url %>">
        <img height="13px" src="/assets/logo.png"/>
      </a>
      <button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="<%= login_url %>">Войти</a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_user_not_logged.html.haml
- currentYear = StudyYear.current.first
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %a.navbar-brand{:href => root_url}
        %img{:src => "/assets/logo.png", :height => "13px"}
        - unless currentYear.nil?
          = currentYear.name
      %button.navbar-toggle{"data-target" => "#navbar-main", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbar-main.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => login_url} Войти

app/views/layouts/_user_operator.html.erb
<% loginText  = current_user.try(:second_name) + ' ' + current_user.try(:first_name) + ' ' + current_user.try(:last_name) %>
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_url %>">
        <img height="13px" src="/assets/logo.png"/>
      </a>
      <button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Отделы", departments_path %>
        </li>
        <li>
          <%= link_to  loginText +" (Выход)", logout_path %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_user_operator.html.haml
- currentYear = StudyYear.current.first
- loginText  = current_user.try(:second_name) + ' ' + current_user.try(:first_name) + ' ' + current_user.try(:last_name)
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %a.navbar-brand{:href => root_url}
        %img{:src => "/assets/logo.png", :height => "13px"}
        - unless currentYear.nil?
          = currentYear.name
      %button.navbar-toggle{"data-target" => "#navbar-main", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbar-main.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          =link_to "Все кафедры", departments_path
        %li
          =link_to  loginText +" (Выход)", logout_path

app/views/layouts/_user_simple.html.erb
<% loginText  = current_user.try(:second_name) + ' ' + current_user.try(:first_name) + ' ' + current_user.try(:last_name) %>
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_url %>">
        <img height="13px" src="/assets/logo.png"/>
      </a>
      <button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Отделы", departments_path %>
        </li>
        <li>
          <%= link_to  loginText +" (Выход)", logout_path %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_user_simple.html.haml
- currentYear = StudyYear.current.first
- loginText  = current_user.try(:second_name) + ' ' + current_user.try(:first_name) + ' ' + current_user.try(:last_name)
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %a.navbar-brand{:href => root_url}
        %img{:src => "/assets/logo.png", :height => "13px"}
        - unless currentYear.nil?
          = currentYear.name
      %button.navbar-toggle{"data-target" => "#navbar-main", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbar-main.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          =link_to "Все кафедры", departments_path
        %li
          =link_to  loginText +" (Выход)", logout_path

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>Diplom</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if current_user.nil? %>
      <%= render 'layouts/user_not_logged' %>
    <% elsif current_user.admin? %>
      <%= render 'layouts/user_admin' %>
    <% elsif current_user.operator? %>
      <%= render 'layouts/user_operator' %>
    <% else %>
      <%= render 'layouts/user_simple' %>
    <% end %>
    <div class="container">
      <% if flash[:alert] %>
        <div class="row">
          <div class="col-lg-12">
            <div class="bs-component">
              <div class="alert alert-dismissable alert-danger">
                <p id="notice">
                  <%= flash[:alert] %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <% if flash[:notice] %>
        <div class="row">
          <div class="col-lg-12">
            <div class="bs-component">
              <div class="alert alert-dismissable alert-info">
                <p id="alert">
                  <%= flash[:notice] %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Дипломная работа
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if current_user.nil?
      = render 'layouts/user_not_logged'
    -elsif current_user.admin?
      = render 'layouts/user_admin'
    -elsif current_user.operator?
      = render 'layouts/user_operator'
    -else
      = render 'layouts/user_simple'
    .container
      -if flash[:alert]
        .row
          .col-lg-12
            .bs-component
              .alert.alert-dismissable.alert-danger
                %p#notice= flash[:alert]
      -if flash[:notice]
        .row
          .col-lg-12
            .bs-component
              .alert.alert-dismissable.alert-info
                %p#alert= flash[:notice]
      = yield